from django.urls import path

from .views import (
    AccidentReportView,
    AdminBroadcastView,
    AllEventsPDFView,
    AnalyticsChartsView,
    AnalyticsPDFView,
    AnalyticsSummaryView,
    AttendanceCreateView,
    AttendanceReviewActionView,
    AttendanceReviewListView,
    CommitteeMembershipManageView,
    CommitteeMembershipRemoveView,
    CommitteeReportCreateView,
    CommitteeReportListView,
    CommitteeReportRespondView,
    CreateAdminUserView,
    EventAttendanceToggleView,
    EventCSVReportView,
    EventEndView,
    EventJoinCommitteeView,
    EventDetailView,
    EventListCreateView,
    EventPickView,
    EventPrepareView,
    MyCommitteeStatusView,
    EventStartView,
    ExperienceRatingView,
    ExpenditureView,
    JSONAnalyzeUploadView,
    LiveMetricsView,
    LoginView,
    MeView,
    RegisterView,
)


urlpatterns = [
    path("auth/register/", RegisterView.as_view()),
    path("auth/login/", LoginView.as_view()),
    path("auth/me/", MeView.as_view()),
    path("auth/create-admin/", CreateAdminUserView.as_view()),
    path("events/", EventListCreateView.as_view()),
    path("events/<int:event_id>/", EventDetailView.as_view()),
    path("events/<int:event_id>/my-committee-status/", MyCommitteeStatusView.as_view()),
    path("events/<int:event_id>/prepare/", EventPrepareView.as_view()),
    path("events/<int:event_id>/join-committee/", EventJoinCommitteeView.as_view()),
    path("events/<int:event_id>/committee-members/", CommitteeMembershipManageView.as_view()),
    path(
        "events/<int:event_id>/committee-members/<int:membership_id>/",
        CommitteeMembershipRemoveView.as_view(),
    ),
    path("events/<int:event_id>/start/", EventStartView.as_view()),
    path("events/<int:event_id>/end/", EventEndView.as_view()),
    path("events/<int:event_id>/attendance-toggle/", EventAttendanceToggleView.as_view()),
    path("events/<int:event_id>/pick/", EventPickView.as_view()),
    path("events/<int:event_id>/report.csv", EventCSVReportView.as_view()),
    path("attendance/", AttendanceCreateView.as_view()),
    path("attendance/review/<int:event_id>/", AttendanceReviewListView.as_view()),
    path("attendance/<int:attendance_id>/review/", AttendanceReviewActionView.as_view()),
    path("committee-reports/", CommitteeReportListView.as_view()),
    path("committee-reports/create/", CommitteeReportCreateView.as_view()),
    path("committee-reports/<int:report_id>/respond/", CommitteeReportRespondView.as_view()),
    path("broadcasts/", AdminBroadcastView.as_view()),
    path("accidents/", AccidentReportView.as_view()),
    path("ratings/", ExperienceRatingView.as_view()),
    path("expenditures/", ExpenditureView.as_view()),
    path("analytics/event/<int:event_id>/summary/", AnalyticsSummaryView.as_view()),
    path("analytics/event/<int:event_id>/charts/", AnalyticsChartsView.as_view()),
    path("analytics/event/<int:event_id>/pdf/", AnalyticsPDFView.as_view()),
    path("analytics/pdf/", AllEventsPDFView.as_view()),
    path("analytics/live/", LiveMetricsView.as_view()),
    path("analytics/upload-json/", JSONAnalyzeUploadView.as_view()),
]
