# Generated by Django 5.2.14 on 2026-05-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
