# Generated by Django 5.2.14 on 2026-05-12 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expenditure_price_per_unit_expenditure_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='spent_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
